services:
 VC4SM\Bundle\Command\TestCommand:
    autowire: true
    autoconfigure: true

 VC4SM\Bundle\DataProvider\CredentialCollectionDataProvider:
    tags: [{ name: 'api_platform.collection_data_provider'}]
    autowire: true

 VC4SM\Bundle\DataProvider\CredentialItemDataProvider:
    tags: ['api_platform.item_data_provider']
    autowire: true

 VC4SM\Bundle\Service\ExternalApi:
    autowire: true
    autoconfigure: true

 VC4SM\Bundle\Service\CredentialProviderInterface:
    '@VC4SM\Bundle\Service\ExternalApi'